-- Add rotation tracking to profiles
alter table profiles
  add column current_rotation_day text not null default 'A';

-- Plans: one per check-in, generated by AI
create table plans (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references profiles(id) on delete cascade,
  check_in_id       uuid not null references check_ins(id) on delete cascade,
  created_at        timestamptz default now(),
  rotation_day      text not null,
  today_focus       text,
  mobility          jsonb,
  workout_gym       jsonb,
  workout_home      jsonb,
  nutrition_targets jsonb,
  food_guidance     jsonb,
  coaching_notes    jsonb,
  raw_ai_response   jsonb
);

alter table plans enable row level security;
create policy "own plans" on plans for all using (auth.uid() = user_id);

create index plans_user_id_idx     on plans (user_id);
create index plans_check_in_id_idx on plans (check_in_id);
create index plans_user_recent_idx on plans (user_id, created_at desc);
